apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/opt/gitlab
          name: gitlab-data-storage
        - mountPath: /var/log/gitlab
          name: gitlab-logs-storage
        - mountPath: /etc/gitlab
          name: gitlab-config-storage
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://192.168.49.2:30080'
            gitlab_rails['gitlab_shell_ssh_port'] = 32222
      volumes:
      - name: gitlab-data-storage
        persistentVolumeClaim:
          claimName: gitlab-data-pvc
      - name: gitlab-logs-storage
        persistentVolumeClaim:
          claimName: gitlab-logs-pvc
      - name: gitlab-config-storage
        persistentVolumeClaim:
          claimName: gitlab-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 32222
