apiVersion: v1
kind: Namespace
metadata:
    name: gitlab

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: gitlab
    namespace: gitlab

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: gitlab

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pv-claim
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      serviceAccountName: gitlab
      containers:
      - name: gitlab
        image: benjameto/my-gitlab-docker:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: gitlab-home
          mountPath: /var/gitlab_home
        - name: docker-sock
          mountPath: /var/run/docker.sock
        securityContext:
          runAsUser: 0
          runAsGroup: 994
      volumes:
      - name: gitlab-home
        persistentVolumeClaim:
          claimName: gitlab-pv-claim
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30001
  selector:
    app: gitlab
     